#!/bin/sh

#
# Unsure if this is strictly necessary now as Mastodon 4 introduced 
# GUI elements for 'Media retention'. They don't mention preview cards 
# and the documentation still says to do this. So here it stays, for now.
#

RAILS_ENV=production 

/app/www/bin/tootctl media remove
/app/www/bin/tootctl preview_cards remove